name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Docker login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_ACCESS_TOKEN }}
        run: |
          echo "iniciando login"
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
          echo "finalizando login"

          
      - name: build docker image
        run: |
          docker build -t jdleiva21/myimage:0.0.1 .
          docker build -t jdleiva21/latest .
          
      - name: push docker image
        run: |
          docker push jdleiva21/myimage:0.0.1 
          docker push jdleiva21/myimage
          
    #- name: Build the Docker image
     # run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
